### ISSUE TITLE
Straggling warning

### ISSUE THREAD

**Issue by sjspielman** [clauswilke/dataviz#101]
Hi Claus, 

FYI you have an R output warning at the end of [Chapter 4](https://serialmentor.com/dataviz/color-basics.html#color-as-a-tool-to-highlight) from Figure 4.9 - you may want to change the settings for that R code chunk.

-Stephanie

**Comment by clauswilke** [comment]
Unfortunately the only way to fix this warning is to rebuild the book with all packages in sync, and the book currently doesn't build. :-(

At some point I'll have to make the effort to set up a docker image or other controlled environment to build the book, otherwise fixing things will become too much of a headache.

**Comment by sjspielman** [comment]
> At some point I'll have to make the effort to set up a docker image or other controlled environment to build the book, otherwise fixing things will become too much of a headache.

[Rocker](https://hub.docker.com/r/rocker/tidyverse/) is dead easy to set up, highly recommended. Although if the book doesn't even build I doubt this container will be of much use..

**Comment by clauswilke** [comment]
The idea would be to set up the container, fix all the issues that exist at the time, and then never have the build break again going forward.

**Comment by sjspielman** [comment]
"never have the build break again going forward." famous last words ;)
