### ISSUE TITLE
Enable HTTPS?

### ISSUE THREAD

**Issue by yihui** [clauswilke/dataviz#34]
Hi Claus, I wonder if it is too much trouble for you to enable HTTPS for your website https://serialmentor.com/dataviz/ (you may consider Netlify if you have not used it). I'm asking because I wish to list this book on the homepage of bookdown.org. Thank you!

**Comment by clauswilke** [comment]
It turns out I just had to update my IP address for github pages. This should be working fine by tomorrow.

Do you recommend enforcing HTTPS at all times? Seems overkill for a site that serves publicly available static content.

**Comment by yihui** [comment]
Yes, I strongly recommend enforcing HTTPS at all times, even for static sites. Many reasons for that (you may google for them), but the most obvious one to your readers will be this (you probably don't want your website to be marked as "❗️Not secure"): https://security.googleblog.com/2018/02/a-secure-web-is-here-to-stay.html

If the book is hosted via Github Pages, you might need to push a commit to expedite the generation of the SSL certificate.

**Comment by mikeloukides** [comment]
It's a pain, but I really do think all sites need to move to HTTPS. There
have been some good posts about that recently, specifically about small
static sites, and why even they need to move.

The problem is basically that with HTTP, you're exposed to man in the
middle. And with the current FCC, that man in the middle who's corrupting
your site could even be completely legal: your ISP, or your reader's ISP,
could decide it wants to inject ad content. To say nothing of what people
and organizations with even less ethics than Comcast and AT&T might do.


Mike Loukides
VP, Content Strategy
O'Reilly Media, Inc.

**Comment by yihui** [comment]
I see https://serialmentor.com/dataviz/ is working now. Excellent! Thanks!

**Comment by clauswilke** [comment]
Thanks to both of you for your comments. I’ve disabled http.
